// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_the_beginning = "CgkI6v3Oue4dEAIQAg"; // <GPGSID>
        public const string achievement_boss = "CgkI6v3Oue4dEAIQBg"; // <GPGSID>
        public const string achievement_magnate = "CgkI6v3Oue4dEAIQBQ"; // <GPGSID>
        public const string achievement_billionaire = "CgkI6v3Oue4dEAIQBA"; // <GPGSID>
        public const string achievement_big_boss = "CgkI6v3Oue4dEAIQBw"; // <GPGSID>
        public const string achievement_millionaire = "CgkI6v3Oue4dEAIQAw"; // <GPGSID>
        public const string leaderboard_best_miner = "CgkI6v3Oue4dEAIQAQ"; // <GPGSID>

}

